SUPPORTED_COUNTRIES = {
    'DZ': 'Algeria',
    'AR': 'Argentina',
    'AU': 'Australia',
    'BH': 'Bahrain',
    'BD': 'Bangladesh',
    'BE': 'Belgium',
    'BR': 'Brazil',
    'KH': 'Cambodia',
    'CA': 'Canada',
    'CO': 'Colombia',
    'DK': 'Denmark',
    'EG': 'Egypt',
    'FI': 'Finland',
    'FR': 'France',
    'DE': 'Germany',
    'IN': 'India',
    'IT': 'Italy',
    'JP': 'Japan',
    'KZ': 'Kazakhstan',
    'MY': 'Malaysia',
    'MX': 'Mexico',
    'MA': 'Morocco',
    'NZ': 'New Zealand',
    'PA': 'Panama',
    'PK': 'Pakistan',
    'PE': 'Peru',
    'PL': 'Poland',
    'QA': 'Qatar',
    'SA': 'Saudi Arabia',
    'SG': 'Singapore',
    'ES': 'Spain',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'TH': 'Thailand',
    'TR': 'Turkiye',
    'UK': 'United Kingdom',
    'US': 'United States'
}
